apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tutorial-backstage-nodejs"
  annotations:
    github.com/project-slug: sgahlot/backstage-tutorial-nodejs
    'quay.io/repository-slug': 'sgahlot/keycloak-test'
    vault.io/secrets-path: janus-idp
    'backstage.io/kubernetes-label-selector': 'app: pod-info'
    'backstage.io/kubernetes-namespace': development
spec:
  type: service
  owner: Sandip Gahlot
  lifecycle: experimental
